---
title: "imort_export"
author: "lxh"
date: "Wednesday, October 29, 2014"
output:
  html_document:
    number_sections: yes
    toc: yes
---

http://www.biosino.org/R/R-doc/onepage/R-data_cn.html

# 导入数据 Import

## 导入表格类型文本文件 Table


`read.table()` 是导入表格类型文本文件的基本函数，`read.csv()` 和 `read.delim()` 是两个快捷函数，分别对于逗号分隔的文件和制表符分隔的文件。

导入表格类型的文本文件文件，通常遇到几个问题：

* 是否包含表头 header
* 变量之间用什么分隔 sep
* 是否将字符型转化为因子 stringsAsFactors

### `read.table()`

用法与参数

```{r, eval=FALSE}
read.table(file, header = FALSE, sep = "", quote = "\"'",
           dec = ".", row.names, col.names,
           as.is = !stringsAsFactors,
           na.strings = "NA", colClasses = NA, nrows = -1,
           skip = 0, check.names = TRUE, fill = !blank.lines.skip,
           strip.white = FALSE, blank.lines.skip = TRUE,
           comment.char = "#",
           allowEscapes = FALSE, flush = FALSE,
           stringsAsFactors = default.stringsAsFactors(),
           fileEncoding = "", encoding = "unknown", text)
```

实例

```{r}
t1 <- read.table(file = "datasets/as.txt", header = TRUE, sep = "\t", stringsAsFactors = FALSE )

```

### `read.csv()`

### `read.delim()`

